site_name : Cyber-puit de connaissances
site_url : https://cyber-puit-de-connaissances.com/
docs_dir : Docs
theme : readthedocs

nav: 
  - Accueil : 'accueil.md'

  - Utile :
    - Ecoute de ports : 'ecoute_ports.md'
    - Les sites utiles : 'sites_utiles.md'

  - Reconnaissance : 
    - Reconnaissance Passive : 'reconnaissance_passive.md'
    - Nmap : 
      - Les scans : 'nmap_bases_scan.md'
      - Utile : 'nmap_bases_utiles.md'

  - Exploits :
    - Metasploit : 
      - Les bases : 'metasploit_bases.md'
      - Les exploits : 'metasploit_exploits.md'
      - Les shells : 'metasploit_msfvenom.md'
      - Les post-exploits : 'metasploit_meterpreter.md'
    - Injections : 
      - SQL : 'injections_SQL.md'
      - XSS : 'injections_XSS.md'
      - Bash : 'injections_bash.md'

  - Autres outils :
    - Hydra :
      - Les bases : 'hydra_bases.md'
    - Wireshark :
      - Les bases : 'wireshark_bases.md'
    - Nessus : 
      - Les bases : 'nessus_bases.md'

  - Les protocoles :
    - SMB : 'SMB_exploit_bases.md'
    - TELNET : 'TELNET_exploit_bases.md'
    - FTP : 'FTP_exploit_bases.md'
    - NFS : 'NFS_exploit_bases.md'
    - SSH : 'SSH_exploit_bases.md'
    - SMTP : 'SMTP_exploit_bases.md'

  - Web : 
    - Les bases : 'web_exploit_bases.md'

  - Wifi :
    - Wifi mdp cracking : 'wifi-cracking.md'

  - Autre services :
    - MySQL : 'MySQL_exploit_bases.md'

  - Les OS :
    - Windows : 'vide.md'
      
    - Linux : 
      - Commandes utiles : 'linux_commandes_utiles.md'
      


  
  - Réseau : 
    - Changer DNS : 'changer_DNS_windows.md'

  - Système :
    - BIOS : 
      - Accès au hardware : 
        - PC fixe : 'reset_mdp_BIOS_hardware_PC_fixe.md'
        - PC portable : 'reset_mdp_BIOS_hardware_PC_portable.md'
